### ISSUE TITLE
PETSCII version of "white circle" missing

### ISSUE THREAD

**Issue by uli** [damianvila/font-bescii#2]
It seems to me that there is no equivalent to the PETSCII "white circle" (0x77) that pairs with the PETSCII "bullet" (0x71) in the font. The glyph mapped to "white circle" is larger and doesn't match visually.

**Comment by damianvila** [comment]
Thanks for the info! I'll update it as soon as I can. I'll also be adding Cyrillic support to the font, as requested in the forum, using the reference that was provided.

**Comment by damianvila** [comment]
@uli I've been researching. You're correct that 0x77 is not there, and 0x71 is at \u2022 (bullet) . There are two additional circle shapes: \u25CF (black circle) and \u25CB (white circle). I'm inclined to include the missing glyph at \u25E6 (white bullet), which seems appropriate for the case, as it will honour Unicode naming. I hope it's a satisfactory solution. 😊

**Comment by damianvila** [comment]
New version in beta with missing white bullet.

**Comment by damianvila** [comment]
White bullet character included at point \u25E6 in the next version of the font.
